### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by xai** [wAmpIre/nntp2mbox#1]
Hi,

I'd like to do something very similar to your nntp2mbox, but need to make some smaller changes (e.g., change the default behaviour which messages are pulled, introduce an optional auto-sleep every N messages to reduce load on the remote-site because gmane blocks the ***\* out of us if we don't, ...).

Unfortunately, your code is not licensed explicitly, so according to https://help.github.com/articles/open-source-licensing/ the default copyright applies and I am therefore not allowed to publicly fork and adapt it:

> This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

Could you explicitly license the code with some open source license of your preference?

Kind regards,
xai

**Comment by wAmpIre** [comment]
[X] Done

Have fun ;-)

**Comment by xai** [comment]
Thank you!
